name: bluetooth_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_datetime_picker_plus: ^2.2.0
  uuid: ^4.4.2
  intl: ^0.19.0
  blue_thermal_printer: ^1.2.3
  flutter_blue: ^0.8.0
  charset_converter: ^2.2.1
  image: ^4.2.0
  translit: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11


flutter:
  uses-material-design: true

assets:
  - images/ggg.jpeg

