name: bluetooth_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_datetime_picker_plus: ^2.2.0
  uuid: ^4.4.2
  intl: ^0.19.0
  image: ^3.0.2
  flutter_blue_plus: ^1.32.12
  path_provider: ^2.1.4
  flutter_spinkit: ^5.2.1
  modal_bottom_sheet: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_libserialport: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11


flutter:
  uses-material-design: true

  assets:
    - assets/images/ggg.jpeg
    - assets/images/test.bmp
    - assets/fonts/roboto.ttf
    - assets/fonts/roboto.zip
    - assets/fonts/roboto.ttf.zip
